dependency wiring: ignore "Require-Bundle: self"
Seen in Eclipse 2023-12, org.eclipse.mylyn.jenkins.core declares
"Require-Bundle: org.eclipse.mylyn.jenkins.core", causing
IllegalStateException: circular dependency detected in
org.eclipse.mylyn.jenkins.core -> org.eclipse.mylyn.jenkins.core

Since "Require-Bundle: self" is valid on the OSGi level, we need to
ignore such a wiring during build order calculation.

Change-Id: I677daf88f0980aedea7f1f60501710108507697c